### ISSUE TITLE
can't find the log viewer in the administrator

### ISSUE THREAD

**Issue by zspitzer** [paulklinkenberg/lucee-loganalyzer#1]
Just installed the extension under Lucee 5.2.3.35, but i can't see it? where should it appear?

**Comment by paulklinkenberg** [comment]
Hi Zac,
The reason you are not seeing the extension, is because Lucee admin caches the extensions. By appending "?alwaysnew=1" to the admin url, it is supposed to show up. Logging out and back in might help, and a good old-fashioned "restart Lucee" from the server admin menu helps for sure.
Sorry for the inconvenience.

Kind regards,

Paul Klinkenberg
------------



Op 20 sep. 2017 om 04:00 heeft Zac Spitzer <notifications@github.com> het volgende geschreven:

Just installed the extension under Lucee 5.2.3.35, but i can't see it? where should it appear?

**Comment by zspitzer** [comment]
thanks! I voted for the bug https://luceeserver.atlassian.net/browse/LDEV-1022

**Comment by paulklinkenberg** [comment]
I voted as well :)

Op 20 sep. 2017, om 09:14 heeft Zac Spitzer <notifications@github.com> het volgende geschreven:

thanks! I voted for the bug https://luceeserver.atlassian.net/browse/LDEV-1022 <https://luceeserver.atlassian.net/browse/LDEV-1022>
